version: '3.8'
volumes:
  db_data:
  node_modules:
  docker-node-modules:
  docker-nx-cache:
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/reverseProxy.conf:/etc/nginx/reverseProxy.conf
    ports:
      - 8000:80
  frontend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/usr/app/node_modules
    command: 'npx nx serve frontend --host 0.0.0.0'
    ports:
      - 4200:4200
  backend:
    image: node:lts
    working_dir: /app
    environment:
      PORT: 3001
      POSTGRES_HOST:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./:/app/
      - docker-node-modules:/app/node_modules
      - docker-nx-cache:/app/.nx
    command: 'npx nx serve backend'
    ports:
      - 3001:3001
      - 9229:9229
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: project2024
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salasana
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
